export type NotificationRole = 'customer' | 'driver' | 'admin';

export interface NotificationPayload {
  type: string;
  title: string;
  body: string;
  data?: Record<string, string>;
  androidChannelId?: string;
  sound?: string;
}

export interface NotificationResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

// ─── User Notification Types ──────────────────────────────────────────────────
export enum UserNotificationType {
  FORCE_LOGOUT = 'FORCE_LOGOUT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  OTP_SENT = 'OTP_SENT',
  BOOKING_CONFIRM = 'BOOKING_CONFIRMED',
  BOOKING_CANCEL = 'BOOKING_CANCELLED',
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  RIDE_STARTED = 'RIDE_STARTED',
  DESTINATION_REACHED = 'DESTINATION_REACHED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SOS_RESOLVED = 'SOS_RESOLVED',
  OTP_LIMIT_EXCEEDED = 'OTP_LIMIT_EXCEEDED',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
}

// ─── Driver Notification Types ────────────────────────────────────────────────
export enum DriverNotificationType {
  FORCE_LOGOUT = 'FORCE_LOGOUT',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  NEW_RIDE_REQUEST = 'NEW_RIDE_REQUEST',
  RIDE_CANCELLED = 'RIDE_CANCELLED',
  RIDE_ASSIGNED = 'RIDE_ASSIGNED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  WALLET_CREDITED = 'WALLET_CREDITED',
  WALLET_DEBITED = 'WALLET_DEBITED',

  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',

  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  SOS_RESOLVED = 'SOS_RESOLVED',
  TRIP_VERIFICATION_APPROVED = 'TRIP_VERIFICATION_APPROVED',
  TRIP_VERIFICATION_REJECTED = 'TRIP_VERIFICATION_REJECTED',
  OTP_LIMIT_EXCEEDED = 'OTP_LIMIT_EXCEEDED',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
}

// ─── Admin Notification Types ─────────────────────────────────────────────────
export enum AdminNotificationType {
  NEW_DRIVER_REGISTERED = 'NEW_DRIVER_REGISTERED',
  NEW_USER_REGISTERED = 'NEW_USER_REGISTERED',
  DOCUMENT_SUBMITTED = 'DOCUMENT_SUBMITTED',
  COMPLAINT_RAISED = 'COMPLAINT_RAISED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
